# Generated by Django 3.1.6 on 2021-02-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mileage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
